(deftheme xterm16
  "Created 2015-06-12.")

(custom-theme-set-faces
 'xterm16
 '(bold ((t (:bold t))))
 '(button ((t (:foreground "#0087af" :underline t))))
 '(header-line ((t (:background "#777" :foreground "#a8a8a8"))))
 '(highlight ((t (:background "#151515"))))
 '(info-xref ((t (:foreground "#0087af" :underline t))))
 '(region ((t (:background "#444"))))
 '(underline ((nil (:underline t))))
 '(font-lock-builtin-face ((t (:foreground "#00af87"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#8787af"))))
 '(font-lock-comment-face ((t (:foreground "#8787af"))))
 '(font-lock-constant-face ((t (:foreground "#8700d7"))))
 '(font-lock-doc-face ((t (:foreground "#87afaf"))))
 '(font-lock-function-name-face ((t (:foreground "#a8a8a8"))))
 '(font-lock-keyword-face ((t (:foreground "#0087af"))))
 '(font-lock-negation-char-face ((t (:foreground "#9d7a04"))))
 '(font-lock-preprocessor-face ((t (:foreground "#0087af"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#9d7"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#9d7"))))
 '(font-lock-string-face ((t (:foreground "#87afaf"))))
 '(font-lock-type-face ((t (:foreground "#00af87"))))
 '(font-lock-variable-name-face ((t (:foreground "#00afaf"))))
 '(font-lock-warning-face ((t (:foreground "#9d7a04"))))
 '(fringe ((t (:background "#111"))))
 '(linum ((t (:foreground "#fffaaa"))))
 '(minibuffer-prompt ((t (:foreground "#00afaf"))))
 '(mode-line ((t (:background "#777" :foreground "#333333"))))
 '(mode-line-inactive ((t (:background "#555" :foreground "#222"))))
 '(cursor ((t (:background "#FFFAAA"))))
 '(vertical-border ((t (:background "#555" :foreground "#222"))))
 '(isearch ((t (:background "#9d7" :foreground "#444"))))
 '(isearch-fail ((t (:background "#9d7a04"))))
 '(lazy-highlight ((t (:background "#00af87" :foreground "#444"))))
 '(default ((t (:background "#111" :foreground "#a8a8a8")))))

(provide-theme 'xterm16)
